### ISSUE TITLE
Building on Ubuntu 18.04 fails with `static declaration of 'getentropy' follows non-static declaration`

### ISSUE THREAD

**Issue by caleblloyd** [ScaleFT/nginx_auth_accessfabric#8]
Trying to build on Ubuntu 18.04 and get the following failure:

```
cc -c -fPIC -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /opt/local-libxjwt/usr/local/include -I objs -I src/http -I src/http/modules \
	-o objs/addon/nginx_auth_accessfabric/ngx_http_auth_accessfabric_module.o \
	../nginx_auth_accessfabric/ngx_http_auth_accessfabric_module.c
../nginx_auth_accessfabric/ngx_http_auth_accessfabric_module.c:757:12: error: static declaration of 'getentropy' follows non-static declaration
 static int getentropy(void *buf, size_t buflen) {
            ^~~~~~~~~~
In file included from src/os/unix/ngx_linux_config.h:20:0,
                 from src/core/ngx_config.h:26,
                 from ../nginx_auth_accessfabric/ngx_http_auth_accessfabric_module.c:18:
/usr/include/unistd.h:1167:5: note: previous declaration of 'getentropy' was here
 int getentropy (void *__buffer, size_t __length) __wur;
     ^~~~~~~~~~
objs/Makefile:1204: recipe for target 'objs/addon/nginx_auth_accessfabric/ngx_http_auth_accessfabric_module.o' failed
make[1]: Leaving directory '/opt/nginx/nginx-1.14.0'
make[1]: *** [objs/addon/nginx_auth_accessfabric/ngx_http_auth_accessfabric_module.o] Error 1
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by caleblloyd** [comment]
Here is my fork with the Dockerfile that I am trying to use:

https://github.com/caleblloyd/nginx_auth_accessfabric/blob/f_docker/docker/build/Dockerfile

**Comment by caleblloyd** [comment]
When I change the base image to `ubuntu:16.04`, it builds fine.  I'll leave the 18.04 branch up for reference and move ahead using 16.04
